version: '3'

services:

  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: /docker/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
